create extension if not exists pgcrypto;

create table if not exists public.instagram_post_queue (
    id bigint generated by default as identity primary key,
    week_key text not null,
    position integer not null,
    source_id text not null,
    departure_city text not null,
    arrival_city text not null,
    travel_date timestamptz null,
    price numeric(10, 2) not null,
    currency text not null,
    booking_url text null,
    flight_payload jsonb not null,
    status text not null default 'queued',
    attempt_count integer not null default 0,
    last_error text null,
    photo_url text null,
    photo_payload jsonb null,
    rendered_image_url text null,
    caption text null,
    publish_response jsonb null,
    processing_started_at timestamptz null,
    posted_at timestamptz null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint instagram_post_queue_week_position_key unique (week_key, position),
    constraint instagram_post_queue_status_check check (
        status in ('queued', 'processing', 'posted', 'retryable_failed', 'failed')
    )
);

create index if not exists instagram_post_queue_week_status_idx
    on public.instagram_post_queue (week_key, status, position);

create table if not exists public.instagram_post_runs (
    id bigint generated by default as identity primary key,
    trigger_source text not null,
    week_key text not null,
    queue_item_id bigint null references public.instagram_post_queue(id) on delete set null,
    status text not null default 'started',
    result jsonb null,
    error text null,
    started_at timestamptz not null default timezone('utc', now()),
    finished_at timestamptz null,
    constraint instagram_post_runs_status_check check (
        status in ('started', 'skipped', 'posted', 'failed')
    )
);

create or replace function public.set_instagram_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_instagram_post_queue_updated_at on public.instagram_post_queue;

create trigger trg_instagram_post_queue_updated_at
before update on public.instagram_post_queue
for each row
execute function public.set_instagram_queue_updated_at();

create or replace function public.claim_next_instagram_queue_item(p_week_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    claimed_row public.instagram_post_queue;
begin
    with candidate as (
        select id
        from public.instagram_post_queue
        where week_key = p_week_key
          and status in ('queued', 'retryable_failed')
        order by position asc, id asc
        limit 1
        for update skip locked
    )
    update public.instagram_post_queue queue
    set status = 'processing',
        attempt_count = queue.attempt_count + 1,
        processing_started_at = timezone('utc', now()),
        last_error = null
    from candidate
    where queue.id = candidate.id
    returning queue.* into claimed_row;

    if claimed_row.id is null then
        return null;
    end if;

    return to_jsonb(claimed_row);
end;
$$;
