create table if not exists public.instagram_post_revisions (
    id bigint generated by default as identity primary key,
    queue_item_id bigint not null references public.instagram_post_queue(id) on delete cascade,
    revision_number integer not null,
    generation_trigger text not null,
    instructions text null,
    rendered_image_url text not null,
    caption text not null,
    photo_url text null,
    photo_payload jsonb null,
    generation_payload jsonb null,
    created_at timestamptz not null default timezone('utc', now()),
    constraint instagram_post_revisions_queue_revision_key unique (queue_item_id, revision_number)
);

alter table public.instagram_post_queue
    add column if not exists current_revision integer not null default 0,
    add column if not exists last_generation_instructions text null,
    add column if not exists generated_at timestamptz null,
    add column if not exists approved_at timestamptz null,
    add column if not exists publishing_started_at timestamptz null,
    add column if not exists selected_platforms jsonb not null default '["instagram"]'::jsonb;

alter table public.instagram_post_queue
    drop constraint if exists instagram_post_queue_status_check;

update public.instagram_post_queue
set status = case
    when status = 'processing' and rendered_image_url is not null and caption is not null then 'review'
    when status = 'processing' then 'generation_failed'
    when status = 'retryable_failed' then 'generation_failed'
    else status
end
where status in ('processing', 'retryable_failed');

update public.instagram_post_queue
set selected_platforms = '["instagram"]'::jsonb
where selected_platforms is null;

alter table public.instagram_post_queue
    add constraint instagram_post_queue_status_check check (
        status in ('queued', 'generating', 'review', 'publishing', 'posted', 'generation_failed', 'failed')
    );

alter table public.instagram_post_runs
    drop constraint if exists instagram_post_runs_status_check;

alter table public.instagram_post_runs
    add constraint instagram_post_runs_status_check check (
        status in ('started', 'skipped', 'generated', 'posted', 'failed')
    );

create or replace function public.claim_next_instagram_queue_item(p_week_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    claimed_row public.instagram_post_queue;
begin
    with candidate as (
        select id
        from public.instagram_post_queue
        where week_key = p_week_key
          and status in ('queued', 'generation_failed')
        order by position asc, id asc
        limit 1
        for update skip locked
    )
    update public.instagram_post_queue queue
    set status = 'generating',
        attempt_count = queue.attempt_count + 1,
        processing_started_at = timezone('utc', now()),
        last_error = null
    from candidate
    where queue.id = candidate.id
    returning queue.* into claimed_row;

    if claimed_row.id is null then
        return null;
    end if;

    return to_jsonb(claimed_row);
end;
$$;
